# Generated by Django 3.1.6 on 2021-02-18 00:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('uuid', models.UUIDField(default=uuid.UUID('4dfa5c9c-ecdc-43d5-9c2c-c68fcca74bef'), unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField(auto_created=True)),
                ('job_title', models.CharField(max_length=20)),
                ('job_notes', models.TextField(blank=True)),
                ('job_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('job_paid', models.BooleanField(default=False)),
                ('job_uuid', models.UUIDField(default=uuid.UUID('4ead3902-da8c-434d-b6f9-464554d35a42'), unique=True)),
            ],
        ),
    ]
