# Generated by Django 3.1.6 on 2021-02-21 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210220_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c3db84bf-c9c6-4dc0-bba9-2d3899f5b4af'), unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_uuid',
            field=models.UUIDField(default=uuid.UUID('a6032b2a-0189-4df7-a39a-d3ad6d73821d'), unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.UUIDField(default=uuid.UUID('b9f5afe7-d2ce-400b-946e-4a7220b62a9c'), unique=True),
        ),
    ]
