# Generated by Django 3.1.6 on 2021-02-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210222_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
