# Generated by Django 3.1.6 on 2021-03-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='fcm_token',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
