# Generated by Django 3.1.6 on 2021-03-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_session_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='fcm_token',
            field=models.CharField(max_length=100),
        ),
    ]
