# Generated by Django 3.1.6 on 2021-03-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210309_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='fcm_token',
            field=models.TextField(),
        ),
    ]
