# Generated by Django 3.1.6 on 2021-03-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
