# Generated by Django 3.1.6 on 2021-03-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactrequest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
