# Generated by Django 3.1.6 on 2021-03-18 00:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactrequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
